apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluentdloki.fullname" . }}
  labels:
    {{- include "fluentdloki.labels" . | nindent 4 }}
data:
  fluent.conf: |
<source>
  @type  forward
  @id    input1
  @label @mainstream
  port  24224
</source>

<filter **>
  @type stdout
</filter>

<label @mainstream>
  <match docker.**>
    @type file
    @id   output_docker1
    path         /fluentd/log/docker.*.log
    symlink_path /fluentd/log/docker.log
    append       true
    time_slice_format %Y%m%d
    time_slice_wait   1m
    time_format       %Y%m%dT%H%M%S%z
  </match>
  <match **>
    @type file
    @id   output1
    path         /fluentd/log/data.*.log
    symlink_path /fluentd/log/data.log
    append       true
    time_slice_format %Y%m%d
    time_slice_wait   10m
    time_format       %Y%m%dT%H%M%S%z
  </match>
@include loki.conf
</label>

  loki.conf: |
<match loki.**>
  @type loki
  url "#{ENV['LOKI_URL']}"
  extra_labels {"job":"fluentd"}
  <buffer>
    flush_interval 10s
    flush_at_shutdown true
  </buffer>
</match>