apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "fluentdloki.fullname" . }}
  labels:
    {{- include "fluentdloki.labels" . | nindent 4 }}
data:
  fluent.conf: |
    <source>
      @type http
      add_http_headers true
      bind 0.0.0.0
      body_size_limit 32m
      keepalive_timeout 10s
      port  24224
    </source>
    <match **>
      @type loki
      <label>
        HTTP_SERVER
      </label>
      url "http://loki:3100"
      extra_labels {"env":"dev"}
      flush_interval 10s
      flush_at_shutdown true
      buffer_chunk_limit 1m
    </match>